name: Deploy GCP Function to US Central

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy Cloud Function
      run: |
        gcloud functions deploy m-tt \
          --region=us-central1 \
          --runtime=python312 \
          --entry-point=main_run \
          --source=. \
          --trigger-http \
          --allow-unauthenticated \
          --set-env-vars: |
            DATASET_ID=${{ secrets.DATASET_ID }},
            PROJECT_ID=${{ secrets.PROJECT_ID }},
            TABLE_ID=${{ secrets.TABLE_ID }},
            LOG_EXECUTION_ID=${{ secrets.LOG_EXECUTION_ID }},
            CONSUMER_KEY=${{ secrets.CONSUMER_KEY }},
            CONSUMER_SECRET=${{ secrets.CONSUMER_SECRET }},
            ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }},
            ACCESS_SECRET=${{ secrets.ACCESS_SECRET }},
            BEARER_TOKEN=${{ secrets.BEARER_TOKEN }}
          --service-account=86383374932-compute@developer.gserviceaccount.com \
          --memory=512Mi \
          --cpu=333m \
          --max-instances=5 \
          --timeout=60s